name: action

on:
  pull_request:
    branches:    
      - dev 

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.after }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-for-dev.txt
        pyppeteer-install
        apt-get install -yq --no-install-recommends \
          libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
          libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
          libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
          libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
          libnss3
    - name: Test with pytest
      run: python -m pytest test_extractor.py --verbose

  build:
    needs: test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Docker Login
      run: docker login -u panoslin -p ${{secrets.DOCKERHUB_LOGIN_PASSWORD}}
    - name: Build the Docker image
      run: docker build --tag panoslin/extractor:${{github.sha}} .
    - name: Push the Docker image
      run: docker push panoslin/extractor
      
  deployment:
    needs: [test, build]
    runs-on: ubuntu-18.04
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DOS }}
        username: ${{ secrets.USERNAME_DOS }}
        password: ${{ secrets.PASSWORD_DOS }}
        script: ${{ secrets.UPDATE_SERVICE }}
    














