name: Docker Image CI

on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - name: Docker Login
      run: docker login -u panoslin -p ${{secrets.DOCKERHUB_LOGIN_PASSWORD}}
    - name: Build the Docker image
      run: docker build --tag panoslin/extractor:$(date +%s) .
    - name: Push the Docker image
      run: docker push panoslin/extractor
